[package]
name = "moirai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "moirai"
crate-type = ["rlib"]

[dependencies]
chrono = {version = "0.4.40", features = ["serde"] }
petgraph = "0.8.1"
pyo3 = "0.24.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tempfile = "3.20.0"
thiserror = "2.0.12"
tokio = {version = "1.44.2", features = ["full"]}
toml = "0.8.22"
